// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.rest;

import ee.ut.rest.SiteEngineerResource;

privileged aspect SiteEngineerResource_Roo_JavaBean {
    
    public String SiteEngineerResource.getName() {
        return this.name;
    }
    
    public void SiteEngineerResource.setName(String name) {
        this.name = name;
    }
    
}
