
package ee.ut.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PlantSOAPService", targetNamespace = "http://web.soap.ut.ee/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PlantSOAPService {


    /**
     * 
     * @param startDate
     * @param endDate
     * @return
     *     returns ee.ut.soap.client.PlantResourceList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailablePlants", targetNamespace = "http://web.soap.ut.ee/", className = "ee.ut.soap.client.GetAvailablePlants")
    @ResponseWrapper(localName = "getAvailablePlantsResponse", targetNamespace = "http://web.soap.ut.ee/", className = "ee.ut.soap.client.GetAvailablePlantsResponse")
    @Action(input = "http://web.soap.ut.ee/PlantSOAPService/getAvailablePlantsRequest", output = "http://web.soap.ut.ee/PlantSOAPService/getAvailablePlantsResponse")
    public PlantResourceList getAvailablePlants(
        @WebParam(name = "startDate", targetNamespace = "http://web.soap.ut.ee/")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://web.soap.ut.ee/")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param purchaseOrder
     * @return
     *     returns ee.ut.soap.client.PurchaseOrderResource
     * @throws NotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPurchaseOrder", targetNamespace = "http://web.soap.ut.ee/", className = "ee.ut.soap.client.CreatePurchaseOrder")
    @ResponseWrapper(localName = "createPurchaseOrderResponse", targetNamespace = "http://web.soap.ut.ee/", className = "ee.ut.soap.client.CreatePurchaseOrderResponse")
    @Action(input = "http://web.soap.ut.ee/PlantSOAPService/createPurchaseOrderRequest", output = "http://web.soap.ut.ee/PlantSOAPService/createPurchaseOrderResponse", fault = {
        @FaultAction(className = NotFoundException_Exception.class, value = "http://web.soap.ut.ee/PlantSOAPService/createPurchaseOrder/Fault/NotFoundException")
    })
    public PurchaseOrderResource createPurchaseOrder(
        @WebParam(name = "purchaseOrder", targetNamespace = "http://web.soap.ut.ee/")
        PurchaseOrderResource purchaseOrder)
        throws NotFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns ee.ut.soap.client.PlantResourceList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPlants", targetNamespace = "http://web.soap.ut.ee/", className = "ee.ut.soap.client.GetAllPlants")
    @ResponseWrapper(localName = "getAllPlantsResponse", targetNamespace = "http://web.soap.ut.ee/", className = "ee.ut.soap.client.GetAllPlantsResponse")
    @Action(input = "http://web.soap.ut.ee/PlantSOAPService/getAllPlantsRequest", output = "http://web.soap.ut.ee/PlantSOAPService/getAllPlantsResponse")
    public PlantResourceList getAllPlants();

}
