// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.model;

import ee.ut.model.RequestedPlant;
import ee.ut.model.RequestedPlantDataOnDemand;
import ee.ut.model.Supplier;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RequestedPlantDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RequestedPlantDataOnDemand: @Component;
    
    private Random RequestedPlantDataOnDemand.rnd = new SecureRandom();
    
    private List<RequestedPlant> RequestedPlantDataOnDemand.data;
    
    public RequestedPlant RequestedPlantDataOnDemand.getNewTransientRequestedPlant(int index) {
        RequestedPlant obj = new RequestedPlant();
        setDescription(obj, index);
        setExternalId(obj, index);
        setSupplier(obj, index);
        return obj;
    }
    
    public void RequestedPlantDataOnDemand.setDescription(RequestedPlant obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void RequestedPlantDataOnDemand.setExternalId(RequestedPlant obj, int index) {
        String externalId = "externalId_" + index;
        obj.setExternalId(externalId);
    }
    
    public void RequestedPlantDataOnDemand.setSupplier(RequestedPlant obj, int index) {
        Supplier supplier = null;
        obj.setSupplier(supplier);
    }
    
    public RequestedPlant RequestedPlantDataOnDemand.getSpecificRequestedPlant(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        RequestedPlant obj = data.get(index);
        Long id = obj.getId();
        return RequestedPlant.findRequestedPlant(id);
    }
    
    public RequestedPlant RequestedPlantDataOnDemand.getRandomRequestedPlant() {
        init();
        RequestedPlant obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return RequestedPlant.findRequestedPlant(id);
    }
    
    public boolean RequestedPlantDataOnDemand.modifyRequestedPlant(RequestedPlant obj) {
        return false;
    }
    
    public void RequestedPlantDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = RequestedPlant.findRequestedPlantEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'RequestedPlant' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<RequestedPlant>();
        for (int i = 0; i < 10; i++) {
            RequestedPlant obj = getNewTransientRequestedPlant(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
