// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.model;

import ee.ut.model.Engineer;

privileged aspect Engineer_Roo_JavaBean {
    
    public String Engineer.getName() {
        return this.name;
    }
    
    public void Engineer.setName(String name) {
        this.name = name;
    }
    
}
